### ISSUE TITLE
Cannot start 

### ISSUE THREAD

**Issue by buscon** [portalmod/mod-panel#3]
hi,

I am runnig Mod panel but I cannot start either the Host+UI or the SDK.
Jack is up and running.

When I start the Host+UI, the mod monitor shortly appear in Claudia, but it disappears immediately.
I do not get any error either, here are the logs:
MOD Host:
lilv_world_load_bundle(): warning: Ignoring bundle <file:///usr/lib/lv2/fat1.lv2/>
lilv_world_load_bundle(): note: Newer version of <http://gareus.org/oss/lv2/fat1> loaded from <file:///home/marcello/.lv2/fat1.lv2/>
lilv_world_load_bundle(): warning: Ignoring bundle <file:///usr/lib/lv2/darc.lv2/>
lilv_world_load_bundle(): note: Newer version of <http://gareus.org/oss/lv2/darc#mono> loaded from <file:///home/marcello/.lv2/darc.lv2/>
mod-host ready!

MOD UI
virtualenv 20.14.1 from /home/marcello/.local/lib/python3.8/site-packages/virtualenv/__init__.py

MOD SDK
virtualenv 20.14.1 from /home/marcello/.local/lib/python3.8/site-packages/virtualenv/__init__.py

**Comment by falkTX** [comment]
claudia/ladish does not support applications that use multiple clients, as mod-host does.

**Comment by buscon** [comment]
ok, then what should I do? uninstall claudia?

**Comment by falkTX** [comment]
use something else?

**Comment by buscon** [comment]
even if I do not use claudia/cadence and I start jack with qjackctl or command line, mod-panel cannot start (same behaviour as above)

**Comment by falkTX** [comment]
what do you mean, from the logs you shown mod-host starts just fine.

**Comment by buscon** [comment]
I mean: the problem does not seem to be related to claudia/cadence.
When I start the mod-panel, it quits after a few seconds, but I do not get any error in the logs.

Is there anyway to increase the verbosity of the logs?
or what could be the problem?

**Comment by falkTX** [comment]
Check the readme, make sure you have virtualenv and pip installed

**Comment by buscon** [comment]
yes, I have both of them installed.
one question about that: you write they should not be too new or too old, what does that mean?
I have pip 22.1.2 with python3.8

**Comment by falkTX** [comment]
that is the python packages installed by virtualenv
new tornado changed core apis and needs code that targets it to adapt. we cant use the new stuff

**Comment by buscon** [comment]
ok, so which version should I use?

**Comment by falkTX** [comment]
doesnt matter, the right version is picked by virtualenv, that is the point of it.

**Comment by buscon** [comment]
ah, ok, so my issue should not be related to the version....

how can I debug the problem?

**Comment by falkTX** [comment]
run the source/mod-ui.sh scripts manually perhaps

**Comment by buscon** [comment]
ok, thanks!

in that case I get:
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
even though the virtualenv is installed

**Comment by buscon** [comment]
ok, i figured that out: I had two versions of virtualenv. Now I kept only the pip installed version and it works, in Claudia too.

thanks!
